
package com.paypal.svcs.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.paypal.svcs.types.aa.AddBankAccountRequest;
import com.paypal.svcs.types.aa.AddBankAccountResponse;
import com.paypal.svcs.types.aa.AddPaymentCardRequest;
import com.paypal.svcs.types.aa.AddPaymentCardResponse;
import com.paypal.svcs.types.aa.CreateAccountRequest;
import com.paypal.svcs.types.aa.CreateAccountResponse;
import com.paypal.svcs.types.aa.GetUserAgreementRequest;
import com.paypal.svcs.types.aa.GetUserAgreementResponse;
import com.paypal.svcs.types.aa.GetVerifiedStatusRequest;
import com.paypal.svcs.types.aa.GetVerifiedStatusResponse;
import com.paypal.svcs.types.aa.SetFundingSourceConfirmedRequest;
import com.paypal.svcs.types.aa.SetFundingSourceConfirmedResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdaptiveAccountsPortType", targetNamespace = "http://svcs.paypal.com/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.paypal.svcs.types.common.ObjectFactory.class,
    com.paypal.svcs.types.aa.ObjectFactory.class
})
public interface AdaptiveAccountsPortType {


    /**
     * 
     * 				Coutries Supported:
     * 					AU - Australia
     * 					CA - Canada
     * 					CY - Cyprus
     * 					CZ - Czech Republic
     * 					DK - Denmark
     * 					EE - Estonia
     * 					FI - Finland
     * 					FR - France
     * 					DE - Germany
     * 					GR - Greece
     * 					HU - Hungary
     * 					IT - Italy
     * 					LV - Latvia
     * 					LT - Lithuania
     * 					LU - Luxembourg
     * 					MT - Malta
     * 					NL - Netherlands
     * 					PL - Poland
     * 					PT - Portugal
     * 					SK - Slovak Republic
     * 					SI - Slovenia
     * 					ES - Spain
     * 					SE - Sweden
     * 					UK - United Kingdom
     * 					US - United States
     * 			
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.aa.CreateAccountResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "CreateAccount", action = "urn:CreateAccount")
    @WebResult(name = "CreateAccountResponse", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
    public CreateAccountResponse createAccount(
        @WebParam(name = "CreateAccountRequest", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
        CreateAccountRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * 				Countries Supported:
     * 					AU - Australia
     * 					AT - Austria  
     * 					CA - Canada
     * 					CZ - Czech Republic
     * 					EU - European Union *
     * 					FR - France
     * 					DE - Germany
     * 					GB - Great Britain
     * 					GR - Greece
     * 					IE - Ireland
     * 					IL - Israel
     * 					IT - Italy
     * 					JP - Japan
     * 					NL - Netherlands
     * 					NZ - New Zealand (Aotearoa)
     * 					PL - Poland
     * 					PT - Portugal
     * 					RU - Russian Federation
     * 					SG - Singapore
     * 					ZA - South Africa
     * 					ES - Spain
     * 					CH - Switzerland  
     * 					US - United States
     * 					* technically a group of countries
     * 			
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.aa.GetUserAgreementResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetUserAgreement", action = "urn:GetUserAgreement")
    @WebResult(name = "GetUserAgreementResponse", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
    public GetUserAgreementResponse getUserAgreement(
        @WebParam(name = "GetUserAgreementRequest", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
        GetUserAgreementRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * 				All countries are supported.
     * 			
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.aa.GetVerifiedStatusResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetVerifiedStatus", action = "urn:GetVerifiedStatus")
    @WebResult(name = "GetVerifiedStatusResponse", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
    public GetVerifiedStatusResponse getVerifiedStatus(
        @WebParam(name = "GetVerifiedStatusRequest", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
        GetVerifiedStatusRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * 				Countries Supported:
     * 					AU - Australia
     * 					CA - Canada
     * 					FR - France
     * 					DE - Germany
     * 					IL - Israel
     * 					IT - Italy
     * 					NL - Netherlands
     * 					UK - United Kingdom
     * 					US - United States
     * 			
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.aa.AddBankAccountResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "AddBankAccount", action = "urn:AddBankAccount")
    @WebResult(name = "AddBankAccountResponse", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
    public AddBankAccountResponse addBankAccount(
        @WebParam(name = "AddBankAccountRequest", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
        AddBankAccountRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * 				Countries Supported:
     * 					AU - Australia
     * 					AT - Austria  
     * 					BE - Belgium
     * 					BR - Brazil
     * 					CA - Canada
     * 					CZ - Czech Republic
     * 					FR - France
     * 					DE - Germany
     * 					GR - Greece
     * 					HK - Hong Kong
     * 					IE - Ireland
     * 					IT - Italy
     * 					JP - Japan
     * 					LU - Luxembourg
     * 					MX - Mexico
     * 					NL - Netherlands
     * 					NZ - New Zealand (Aotearoa)
     * 					PL - Poland
     * 					PT - Portugal
     * 					RU - Russian Federation
     * 					SG - Singapore
     * 					ZA - South Africa
     * 					ES - Spain
     * 					CH - Switzerland  
     * 					UK - United Kingdom
     * 					US - United States
     * 			
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.aa.AddPaymentCardResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "AddPaymentCard", action = "urn:AddPaymentCard")
    @WebResult(name = "AddPaymentCardResponse", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
    public AddPaymentCardResponse addPaymentCard(
        @WebParam(name = "AddPaymentCardRequest", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
        AddPaymentCardRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * 				To be updated.
     * 				Countries Supported:
     * 					AU - Australia
     * 					AT - Austria  
     * 					BE - Belgium
     * 					BR - Brazil
     * 					CA - Canada
     * 					CZ - Czech Republic
     * 					FR - France
     * 					DE - Germany
     * 					GR - Greece
     * 					HK - Hong Kong
     * 					IE - Ireland
     * 					IT - Italy
     * 					JP - Japan
     * 					LU - Luxembourg
     * 					MX - Mexico
     * 					NL - Netherlands
     * 					NZ - New Zealand (Aotearoa)
     * 					PL - Poland
     * 					PT - Portugal
     * 					RU - Russian Federation
     * 					SG - Singapore
     * 					ZA - South Africa
     * 					ES - Spain
     * 					CH - Switzerland  
     * 					UK - United Kingdom
     * 					US - United States
     * 			
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.aa.SetFundingSourceConfirmedResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "SetFundingSourceConfirmed", action = "urn:SetFundingSourceConfirmed")
    @WebResult(name = "SetFundingSourceConfirmedResponse", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
    public SetFundingSourceConfirmedResponse setFundingSourceConfirmed(
        @WebParam(name = "SetFundingSourceConfirmedRequest", targetNamespace = "http://svcs.paypal.com/types/aa", partName = "body")
        SetFundingSourceConfirmedRequest body)
        throws PPFaultMessage
    ;

}
