
package com.paypal.svcs.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.paypal.svcs.types.ap.CancelPreapprovalRequest;
import com.paypal.svcs.types.ap.CancelPreapprovalResponse;
import com.paypal.svcs.types.ap.ConfirmPreapprovalRequest;
import com.paypal.svcs.types.ap.ConfirmPreapprovalResponse;
import com.paypal.svcs.types.ap.ConvertCurrencyRequest;
import com.paypal.svcs.types.ap.ConvertCurrencyResponse;
import com.paypal.svcs.types.ap.ExecutePaymentRequest;
import com.paypal.svcs.types.ap.ExecutePaymentResponse;
import com.paypal.svcs.types.ap.GetAllowedFundingSourcesRequest;
import com.paypal.svcs.types.ap.GetAllowedFundingSourcesResponse;
import com.paypal.svcs.types.ap.GetAvailableShippingAddressesRequest;
import com.paypal.svcs.types.ap.GetAvailableShippingAddressesResponse;
import com.paypal.svcs.types.ap.GetFundingPlansRequest;
import com.paypal.svcs.types.ap.GetFundingPlansResponse;
import com.paypal.svcs.types.ap.GetPaymentOptionsRequest;
import com.paypal.svcs.types.ap.GetPaymentOptionsResponse;
import com.paypal.svcs.types.ap.GetShippingAddressesRequest;
import com.paypal.svcs.types.ap.GetShippingAddressesResponse;
import com.paypal.svcs.types.ap.GetUserLimitsRequest;
import com.paypal.svcs.types.ap.GetUserLimitsResponse;
import com.paypal.svcs.types.ap.PayRequest;
import com.paypal.svcs.types.ap.PayResponse;
import com.paypal.svcs.types.ap.PaymentDetailsRequest;
import com.paypal.svcs.types.ap.PaymentDetailsResponse;
import com.paypal.svcs.types.ap.PreapprovalDetailsRequest;
import com.paypal.svcs.types.ap.PreapprovalDetailsResponse;
import com.paypal.svcs.types.ap.PreapprovalRequest;
import com.paypal.svcs.types.ap.PreapprovalResponse;
import com.paypal.svcs.types.ap.RefundRequest;
import com.paypal.svcs.types.ap.RefundResponse;
import com.paypal.svcs.types.ap.SetPaymentOptionsRequest;
import com.paypal.svcs.types.ap.SetPaymentOptionsResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdaptivePaymentsPortType", targetNamespace = "http://svcs.paypal.com/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.paypal.svcs.types.ap.ObjectFactory.class,
    com.paypal.svcs.types.common.ObjectFactory.class
})
public interface AdaptivePaymentsPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.CancelPreapprovalResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "CancelPreapproval", action = "urn:CancelPreapproval")
    @WebResult(name = "CancelPreapprovalResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public CancelPreapprovalResponse cancelPreapproval(
        @WebParam(name = "CancelPreapprovalRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        CancelPreapprovalRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.ConfirmPreapprovalResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "ConfirmPreapproval", action = "urn:ConfirmPreapproval")
    @WebResult(name = "ConfirmPreapprovalResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public ConfirmPreapprovalResponse confirmPreapproval(
        @WebParam(name = "ConfirmPreapprovalRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        ConfirmPreapprovalRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.ConvertCurrencyResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "ConvertCurrency", action = "urn:ConvertCurrency")
    @WebResult(name = "ConvertCurrencyResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public ConvertCurrencyResponse convertCurrency(
        @WebParam(name = "ConvertCurrencyRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        ConvertCurrencyRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.ExecutePaymentResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "ExecutePayment", action = "urn:ExecutePayment")
    @WebResult(name = "ExecutePaymentResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public ExecutePaymentResponse executePayment(
        @WebParam(name = "ExecutePaymentRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        ExecutePaymentRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.GetAllowedFundingSourcesResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetAllowedFundingSources", action = "urn:GetAllowedFundingSources")
    @WebResult(name = "GetAllowedFundingSourcesResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public GetAllowedFundingSourcesResponse getAllowedFundingSources(
        @WebParam(name = "GetAllowedFundingSourcesRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        GetAllowedFundingSourcesRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.GetPaymentOptionsResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetPaymentOptions", action = "urn:GetPaymentOptions")
    @WebResult(name = "GetPaymentOptionsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public GetPaymentOptionsResponse getPaymentOptions(
        @WebParam(name = "GetPaymentOptionsRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        GetPaymentOptionsRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.PaymentDetailsResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "PaymentDetails", action = "urn:PaymentDetails")
    @WebResult(name = "PaymentDetailsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public PaymentDetailsResponse paymentDetails(
        @WebParam(name = "PaymentDetailsRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        PaymentDetailsRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.PayResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "Pay", action = "urn:Pay")
    @WebResult(name = "PayResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public PayResponse pay(
        @WebParam(name = "PayRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        PayRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.PreapprovalDetailsResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "PreapprovalDetails", action = "urn:PreapprovalDetails")
    @WebResult(name = "PreapprovalDetailsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public PreapprovalDetailsResponse preapprovalDetails(
        @WebParam(name = "PreapprovalDetailsRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        PreapprovalDetailsRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.PreapprovalResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "Preapproval", action = "urn:Preapproval")
    @WebResult(name = "PreapprovalResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public PreapprovalResponse preapproval(
        @WebParam(name = "PreapprovalRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        PreapprovalRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.RefundResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "Refund", action = "urn:Refund")
    @WebResult(name = "RefundResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public RefundResponse refund(
        @WebParam(name = "RefundRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        RefundRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.SetPaymentOptionsResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "SetPaymentOptions", action = "urn:SetPaymentOptions")
    @WebResult(name = "SetPaymentOptionsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public SetPaymentOptionsResponse setPaymentOptions(
        @WebParam(name = "SetPaymentOptionsRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        SetPaymentOptionsRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.GetFundingPlansResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetFundingPlans", action = "urn:GetFundingPlans")
    @WebResult(name = "GetFundingPlansResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public GetFundingPlansResponse getFundingPlans(
        @WebParam(name = "GetFundingPlansRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        GetFundingPlansRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.GetAvailableShippingAddressesResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetAvailableShippingAddresses", action = "urn:GetAvailableShippingAddresses")
    @WebResult(name = "GetAvailableShippingAddressesResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public GetAvailableShippingAddressesResponse getAvailableShippingAddresses(
        @WebParam(name = "GetAvailableShippingAddressesRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        GetAvailableShippingAddressesRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.GetShippingAddressesResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetShippingAddresses", action = "urn:GetShippingAddresses")
    @WebResult(name = "GetShippingAddressesResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public GetShippingAddressesResponse getShippingAddresses(
        @WebParam(name = "GetShippingAddressesRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        GetShippingAddressesRequest body)
        throws PPFaultMessage
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.paypal.svcs.types.ap.GetUserLimitsResponse
     * @throws PPFaultMessage
     */
    @WebMethod(operationName = "GetUserLimits", action = "GetUserLimits")
    @WebResult(name = "GetUserLimitsResponse", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
    public GetUserLimitsResponse getUserLimits(
        @WebParam(name = "GetUserLimitsRequest", targetNamespace = "http://svcs.paypal.com/types/ap", partName = "body")
        GetUserLimitsRequest body)
        throws PPFaultMessage
    ;

}
