
package com.paypal.svcs.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdaptivePayments", targetNamespace = "http://svcs.paypal.com/services", wsdlLocation = "https://svcs.sandbox.paypal.com/AdaptivePayments/Pay?wsdl")
public class AdaptivePayments
    extends Service
{

    private final static URL ADAPTIVEPAYMENTS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.paypal.svcs.services.AdaptivePayments.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.paypal.svcs.services.AdaptivePayments.class.getResource(".");
            url = new URL(baseUrl, "https://svcs.sandbox.paypal.com/AdaptivePayments/Pay?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://svcs.sandbox.paypal.com/AdaptivePayments/Pay?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADAPTIVEPAYMENTS_WSDL_LOCATION = url;
    }

    public AdaptivePayments(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdaptivePayments() {
        super(ADAPTIVEPAYMENTS_WSDL_LOCATION, new QName("http://svcs.paypal.com/services", "AdaptivePayments"));
    }

    /**
     * 
     * @return
     *     returns AdaptivePaymentsPortType
     */
    @WebEndpoint(name = "AdaptivePaymentsSOAP11_http")
    public AdaptivePaymentsPortType getAdaptivePaymentsSOAP11Http() {
        return super.getPort(new QName("http://svcs.paypal.com/services", "AdaptivePaymentsSOAP11_http"), AdaptivePaymentsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdaptivePaymentsPortType
     */
    @WebEndpoint(name = "AdaptivePaymentsSOAP11_http")
    public AdaptivePaymentsPortType getAdaptivePaymentsSOAP11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://svcs.paypal.com/services", "AdaptivePaymentsSOAP11_http"), AdaptivePaymentsPortType.class, features);
    }

}
